# Generated by Django 2.1.2 on 2018-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toylibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gu', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_road', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=25)),
            ],
        ),
    ]
