# Generated by Django 2.1.2 on 2018-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toylibrary',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='toylibrary',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
