# Generated by Django 2.1.2 on 2018-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255)),
                ('end_date', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(blank=True, max_length=255)),
                ('homepage', models.URLField()),
                ('target_user', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.CharField(blank=True, max_length=255, null=True)),
                ('inquiry', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
