# Generated by Django 2.1.3 on 2018-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True)),
                ('end_date', models.TextField(blank=True)),
                ('time', models.TextField(blank=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('target_user', models.TextField(blank=True, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
                ('inquiry', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
