# Generated by Django 2.1.2 on 2018-10-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kidscafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_road', models.CharField(blank=True, max_length=200, null=True)),
                ('tell', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('check_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
