# Generated by Django 2.1.3 on 2018-11-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('use_note', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tell', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
